version: "2"
services:
  web:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"